version: '3'

services:
  db-doc:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: document
    ports:
      - 5432:5432

  pgadmin-doc:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: username@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80