version: '3'

services:
  db-doc:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: document
    ports:
      - 5432:5432

  pgadmin-doc:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: username@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80

  keycloak-doc:
      image: quay.io/keycloak/keycloak:23.0.7
      environment:
        KC_HOSTNAME: localhost
        KC_HOSTNAME_PORT: 8080
        KC_HOSTNAME_STRICT: false
        KC_HOSTNAME_STRICT_HTTPS: false

        KC_LOG_LEVEL: info
        KC_METRICS_ENABLED: true
        KC_HEALTH_ENABLED: true
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      command: start-dev
      depends_on:
        - db-doc
      ports:
        - 8080:8080
